set(__QT_DEPLOY_TARGET_app_FILE /Users/gyeongjinyang/Desktop/project/school/TTD/packet-eye/src/app/libapp.a)
set(__QT_DEPLOY_TARGET_app_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_core_FILE /Users/gyeongjinyang/Desktop/project/school/TTD/packet-eye/src/core/libcore.a)
set(__QT_DEPLOY_TARGET_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_packet-eye_FILE /Users/gyeongjinyang/Desktop/project/school/TTD/packet-eye/packet-eye)
set(__QT_DEPLOY_TARGET_packet-eye_TYPE EXECUTABLE)
